#!/usr/bin/env ruby
require 'ncypher'

begin
  Object.const_get('Ncypher')
rescue NameError
  require 'bundler/setup'
end

SUB_COMMANDS = %w(generate_key encrypt decrypt)

if ARGV.empty?
  STDERR.puts "Ncypher a credential encryption tool"
  STDERR.puts "usage: ncypher generate_key"
  STDERR.puts "usage: ncypher key"
  STDERR.puts "usage: ncypher encrypt <text>"
  STDERR.puts "usage: ncypher decrypt <text>"
  abort
end

cmd = ARGV.shift
case cmd
  when "generate_key"
    puts Ncypher::Ncypher.new.generate_key
  when "key"
    puts Ncypher::Ncypher.new.key_b64
  when "encrypt"
    text = (ARGV.shift || STDIN.read)
    puts Ncypher::Ncypher.new.encrypt(text.strip)
  when "decrypt"
    text = (ARGV.shift || STDIN.read)
    puts Ncypher::Ncypher.new.decrypt(text.strip)
end
